"""
配置模块
提供统一的配置管理功能
"""

from .config_loader import (
    get_config,
    get_server_config,
    get_database_config,
    get_crawler_config,
    get_analysis_config,
    get_logging_config,
    get_task_config,
    get_mobile_cookies,
    get_pc_cookies,
    get_request_timeout,
    get_retry_times,
    get_user_agent,
    get_delay_range,
    get_page_size,
    get_search_max_pages,
    get_repost_max_pages,
    get_mongodb_config,
    get_redis_config,
    is_proxy_enabled,
    get_proxies,
)

__all__ = [
    'get_config',
    'get_server_config',
    'get_database_config',
    'get_crawler_config',
    'get_analysis_config',
    'get_logging_config',
    'get_task_config',
    'get_mobile_cookies',
    'get_pc_cookies',
    'get_request_timeout',
    'get_retry_times',
    'get_user_agent',
    'get_delay_range',
    'get_page_size',
    'get_search_max_pages',
    'get_repost_max_pages',
    'get_mongodb_config',
    'get_redis_config',
    'is_proxy_enabled',
    'get_proxies',
]
